### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by perfect7gentleman**

### CODE REVIEW

**Comment by perfect7gentleman** [comment]
https://github.com/shaohao/vfs_rar/pull/4
patch is here

**Comment by Alexey-Yakovenko** [comment]
The current build fails because of some changes in discord plugin.
I'll need to fix this first, before merging anything new.

**Comment by perfect7gentleman** [comment]
It's strange. I've built it without any errors.

**Comment by Alexey-Yakovenko** [comment]
Not sure what do you mean by strange, you can see build log right here: https://travis-ci.org/github/DeaDBeeF-Player/deadbeef-plugin-builder/builds/664756571?utm_source=github_status&utm_medium=notification

**Comment by perfect7gentleman** [comment]
I want to post a patch, but I don't have right for it.

**Comment by Alexey-Yakovenko** [comment]
> I wanted to post a patch, but I don't have right for it.

what patch and what right?

**Comment by perfect7gentleman** [comment]
the patch for that PR https://github.com/shaohao/vfs_rar/pull/4

**Comment by Alexey-Yakovenko** [comment]
ah, you mean that the plugin dev won't accept your PR?

**Comment by Alexey-Yakovenko** [comment]
Such patch is not acceptable for the plugin builder, since it's not patching build scripts, but actually changes the plugin source code. You need to contact the developer of the plugin, and get the source changes upstream. Also, it seems that 4.patch itself is missing in your commit.

**Comment by perfect7gentleman** [comment]
do 
```
wget https://github.com/shaohao/vfs_rar/pull/4.patch
```
and the patch is here

**Comment by Alexey-Yakovenko** [comment]
I can accept the updated PR, when your patch lands upstream.

**Comment by Alexey-Yakovenko** [comment]
If upstream is not responding for a few days, I'll consider mirroring the repository, and merging your patch there instead.

**Comment by Alexey-Yakovenko** [comment]
I was looking into CI build failure, and had to disable both the ddb_discord_presence, and vfs_rar.
They're both using C++, and both rely on a newer C++ standard than available in deadbeef-plugin-builder SDK.
For now, the only thing I can do is disable them, and in the future I need to consider supporting newer version of C++.

**Comment by Alexey-Yakovenko** [comment]
Hmm.. even after upgrading C++ runtime, and being able to build discord plugin, I still get a weird error with unrar..

```
threadpool.cpp:(.text.startup+0x1c): undefined reference to `__dso_handle'
/usr/bin/ld: .objs/threadpool.o: relocation R_X86_64_PC32 against undefined hidden symbol `__dso_handle' can not be used when making a shared object
/usr/bin/ld: final link failed: Bad value
```

It should be trivial to fix, but I couldn't find what is wrong.
The build commands look correct.

**Comment by Alexey-Yakovenko** [comment]
I already tried:

* Adding various libraries which are supposed to define that symbol
* Defining it manually in one of the sources

Nothing helped. Ideas are welcome.

**Comment by perfect7gentleman** [comment]
You won't be able to build vfs_rar with newer unrar without patch from that PR.

**Comment by Alexey-Yakovenko** [comment]
Cool. Now you need to update the PR, so that it doesn't require the 4.patch.
However, I still can't get a working binary of vfs_rar, and it will stay disabled anyway.

**Comment by Alexey-Yakovenko** [comment]
Current state: builds without errors and produces a seemingly valid binary, but the `tools/pluginfo` utility can't load the plugin and fails silently. Working on this.

**Comment by perfect7gentleman** [comment]
```
starting deadbeef devel
server_start
searching for GUI plugins in /home/USERNAME/.local/lib64/deadbeef
load_plugin_dir /home/USERNAME/.local/lib64/deadbeef: scandir found 3 files
searching for GUI plugins in /home/USERNAME/.local/lib/deadbeef
searching for GUI plugins in /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 18 files
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib64/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/USERNAME/.local/lib64/deadbeef
load_plugin_dir /home/USERNAME/.local/lib64/deadbeef: scandir found 3 files
loading plugin /home/USERNAME/.local/lib64/deadbeef/vfs_rar.so
loading plugins from /home/USERNAME/.local/lib/deadbeef
loading plugins from /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 18 files
loading plugin /usr/lib64/deadbeef/alsa.so
loading plugin /usr/lib64/deadbeef/artwork.so
loading plugin /usr/lib64/deadbeef/converter.so
loading plugin /usr/lib64/deadbeef/converter_gtk3.so
loading plugin /usr/lib64/deadbeef/ffap.so
loading plugin /usr/lib64/deadbeef/flac.so
loading plugin /usr/lib64/deadbeef/hotkeys.so
loading plugin /usr/lib64/deadbeef/m3u.so
loading plugin /usr/lib64/deadbeef/notify.so
loading plugin /usr/lib64/deadbeef/pulse.so
loading plugin /usr/lib64/deadbeef/shellexec.so
loading plugin /usr/lib64/deadbeef/vfs_curl.so
loading plugin /usr/lib64/deadbeef/vfs_zip.so
loading plugin /usr/lib64/deadbeef/wavpack.so
starting plugin GTK3 user interface
starting plugin RAR vfs
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Converter
starting plugin Converter GTK3 UI
starting plugin Monkey's Audio (APE) decoder
starting plugin FLAC decoder
starting plugin Hotkey manager
starting plugin M3U and PLS support
starting plugin OSD Notify
starting plugin PulseAudio output plugin
starting plugin Shell commands
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin WavPack decoder
starting plugin stdio vfs
selected output plugin: ALSA output plugin
INFO: from file /home/USERNAME/.config/deadbeef/playlists/0.dbpl
gtkui plugin compiled for gtk version: 3.24.14
connecting button tray signals
```

**Comment by Alexey-Yakovenko** [comment]
This is not enough, it needs to build in the travis build environment.

**Comment by Alexey-Yakovenko** [comment]
Ok. I realized that what I was trying to do was unsupported and broken, and embraced building the C++ parts with the system-provided libstdc++.

Basically, I was trying to force g++ to link the plugins with a different libstdc++ than what's shipped with g++. This caused all sorts of issues - mainly crashes and missing symbols.

**Pull request closed without merging**
